# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.cache/wt [current_project]
set_property parent.project_path /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/sources_1/new/video_defines.vh
read_verilog -library xil_defaultlib {
  /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/sources_1/new/async_reset.v
  /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/sources_1/new/display_clock.v
  /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/sources_1/new/display_timings.v
  /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/sources_1/new/dvi_generator.v
  /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/sources_1/new/serializer_10to1.v
  /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/sources_1/new/test_card.v
  /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/sources_1/new/tmds_encoder_dvi.v
  /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/sources_1/new/display_demo_dvi.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/10.hdmi_simple/10.hdmi_simple.srcs/constrs_1/new/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top display_demo_dvi -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef display_demo_dvi.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file display_demo_dvi_utilization_synth.rpt -pb display_demo_dvi_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
