# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part2/11.AMP2cores/AMP2cores.srcs/sources_1/bd/pwm_led/ip/pwm_led_auto_pc_0/pwm_led_auto_pc_0.xci
# IP: The module: 'pwm_led_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part2/11.AMP2cores/AMP2cores.srcs/sources_1/bd/pwm_led/ip/pwm_led_auto_pc_0/pwm_led_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_led_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part2/11.AMP2cores/AMP2cores.srcs/sources_1/bd/pwm_led/ip/pwm_led_auto_pc_0/pwm_led_auto_pc_0.xci
# IP: The module: 'pwm_led_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part2/11.AMP2cores/AMP2cores.srcs/sources_1/bd/pwm_led/ip/pwm_led_auto_pc_0/pwm_led_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_led_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
