# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/05.pll/05.pll.srcs/sources_1/ip/clock/clock.xci
# IP: The module: 'clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/05.pll/05.pll.srcs/sources_1/ip/clock/clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/05.pll/05.pll.srcs/sources_1/ip/clock/clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/05.pll/05.pll.srcs/sources_1/ip/clock/clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/05.pll/05.pll.srcs/sources_1/ip/clock/clock.xci
# IP: The module: 'clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/05.pll/05.pll.srcs/sources_1/ip/clock/clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/05.pll/05.pll.srcs/sources_1/ip/clock/clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part1/05.pll/05.pll.srcs/sources_1/ip/clock/clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
