webtalk_init -webtalk_dir /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part2/hello_world/hello_world.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-02-25 17:58:52" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "21n6gi022m6ju9h9tbjg1nfipc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1186.294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.518 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1614250188000" -context "sdk\\\\bsp/1614250188000"
webtalk_add_data -client sdk -key hwid -value "1614248058000" -context "sdk\\\\bsp/1614250188000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1614250188000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1614250188000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1614250188000"
webtalk_add_data -client sdk -key uid -value "1614250189000" -context "sdk\\\\application/1614250189000"
webtalk_add_data -client sdk -key hwid -value "1614248058000" -context "sdk\\\\application/1614250189000"
webtalk_add_data -client sdk -key bspid -value "1614250188000" -context "sdk\\\\application/1614250189000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1614250189000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1614250189000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1614250189000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1614250189000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1614250189000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1614250189000"
webtalk_add_data -client sdk -key projSize -value "127.47265625" -context "sdk\\\\application/1614250189000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1614250732434"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1614250732434"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1614250732434"
webtalk_add_data -client sdk -key DebugCount -value "5" -context "sdk\\\\bsp/1614250732434"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1614250732434"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1614250732434"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1614250732434"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1614250732434"
webtalk_transmit -clientid 2832150948 -regid "" -xml /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part2/hello_world/hello_world.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part2/hello_world/hello_world.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/arif/Documents/1.GitSVN/8.GitHub/zynq_z7lite_training/Tutorial/part2/hello_world/hello_world.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
