# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/arif/Documents/1.GIT/3.Github/zynq_z7lite_training/Tutorial/part1/07.ram_pp/07.ram_pp.srcs/sources_1/ip/ram_wr256x8_rd256x8/ram_wr256x8_rd256x8.xci
# IP: The module: 'ram_wr256x8_rd256x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/arif/Documents/1.GIT/3.Github/zynq_z7lite_training/Tutorial/part1/07.ram_pp/07.ram_pp.srcs/sources_1/ip/ram_wr256x8_rd256x8/ram_wr256x8_rd256x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_wr256x8_rd256x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/arif/Documents/1.GIT/3.Github/zynq_z7lite_training/Tutorial/part1/07.ram_pp/07.ram_pp.srcs/sources_1/ip/ram_wr256x8_rd256x8/ram_wr256x8_rd256x8.xci
# IP: The module: 'ram_wr256x8_rd256x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/arif/Documents/1.GIT/3.Github/zynq_z7lite_training/Tutorial/part1/07.ram_pp/07.ram_pp.srcs/sources_1/ip/ram_wr256x8_rd256x8/ram_wr256x8_rd256x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_wr256x8_rd256x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
