webtalk_init -webtalk_dir /home/drw/Documents/1.GitSVN/4.GitHub/zynq_z7lite_training/Tutorial/part2/12.QSPI_Flash_ReadWrite/12.QSPI_Flash_ReadWrite.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2022-03-21 14:10:07" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "gdnuttpfsgdscg51okdav98n0l" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5500U with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2333.641 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.158 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1647836135000" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1647836135000"
webtalk_add_data -client sdk -key uid -value "1647836180000" -context "sdk\\\\bsp/1647836180000"
webtalk_add_data -client sdk -key hwid -value "1647836135000" -context "sdk\\\\bsp/1647836180000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1647836180000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1647836180000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1647836180000"
webtalk_add_data -client sdk -key uid -value "1647836181000" -context "sdk\\\\application/1647836181000"
webtalk_add_data -client sdk -key hwid -value "1647836135000" -context "sdk\\\\application/1647836181000"
webtalk_add_data -client sdk -key bspid -value "1647836180000" -context "sdk\\\\application/1647836181000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1647836181000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1647836181000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1647836181000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1647836181000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1647836181000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1647836181000"
webtalk_add_data -client sdk -key projSize -value "273.8359375" -context "sdk\\\\application/1647836181000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1647846607788"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1647846607788"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1647846607788"
webtalk_add_data -client sdk -key DebugCount -value "3" -context "sdk\\\\bsp/1647846607788"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1647846607788"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1647846607788"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1647846607788"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1647846607788"
webtalk_transmit -clientid 485603743 -regid "" -xml /home/drw/Documents/1.GitSVN/4.GitHub/zynq_z7lite_training/Tutorial/part2/12.QSPI_Flash_ReadWrite/12.QSPI_Flash_ReadWrite.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/drw/Documents/1.GitSVN/4.GitHub/zynq_z7lite_training/Tutorial/part2/12.QSPI_Flash_ReadWrite/12.QSPI_Flash_ReadWrite.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/drw/Documents/1.GitSVN/4.GitHub/zynq_z7lite_training/Tutorial/part2/12.QSPI_Flash_ReadWrite/12.QSPI_Flash_ReadWrite.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
