webtalk_init -webtalk_dir /home/arif/Documents/1.GIT/3.Github/zynq_z7lite_training/Tutorial/part1/03.breath_led/03.breath_led.sim/sim_1/behav/xsim/xsim.dir/tb_breath_led_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 10 23:07:15 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1b3c760a-4cfb-4d1c-a160-e264de469f30" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "70c02aa0a5a44ec0923944c1765a63c5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600 6-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2255.695 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114912_KB" -context "xsim\\usage"
webtalk_transmit -clientid 134771213 -regid "" -xml /home/arif/Documents/1.GIT/3.Github/zynq_z7lite_training/Tutorial/part1/03.breath_led/03.breath_led.sim/sim_1/behav/xsim/xsim.dir/tb_breath_led_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/arif/Documents/1.GIT/3.Github/zynq_z7lite_training/Tutorial/part1/03.breath_led/03.breath_led.sim/sim_1/behav/xsim/xsim.dir/tb_breath_led_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/arif/Documents/1.GIT/3.Github/zynq_z7lite_training/Tutorial/part1/03.breath_led/03.breath_led.sim/sim_1/behav/xsim/xsim.dir/tb_breath_led_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
