set_property SRC_FILE_INFO {cfile:/home/arif/Documents/1.GIT/3.Github/zynq_z7lite_training/Tutorial/part1/03.breath_led/03.breath_led.srcs/constrs_1/new/top_pin.xdc rfile:../../../03.breath_led.srcs/constrs_1/new/top_pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports led]
