# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ps_lwip.xdc

# Block Designs: bd/ps_lwip/ps_lwip.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_lwip || ORIG_REF_NAME==ps_lwip} -quiet] -quiet

# IP: bd/ps_lwip/ip/ps_lwip_processing_system7_0_0/ps_lwip_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_lwip_processing_system7_0_0 || ORIG_REF_NAME==ps_lwip_processing_system7_0_0} -quiet] -quiet

# IP: bd/ps_lwip/ip/ps_lwip_xlconcat_0_0/ps_lwip_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_lwip_xlconcat_0_0 || ORIG_REF_NAME==ps_lwip_xlconcat_0_0} -quiet] -quiet

# IP: bd/ps_lwip/ip/ps_lwip_xlconcat_1_0/ps_lwip_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_lwip_xlconcat_1_0 || ORIG_REF_NAME==ps_lwip_xlconcat_1_0} -quiet] -quiet

# XDC: bd/ps_lwip/ps_lwip_ooc.xdc
